// <auto-generated />
using System;
using EquifyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EquifyAPI.Migrations
{
    [DbContext(typeof(EquifyContext))]
    partial class EquifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("EquifyAPI.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DealOriginationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DealStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("DealTeamLead")
                        .HasColumnType("TEXT");

                    b.Property<string>("DealType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ESGLead")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnterpriseValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EquityRequired")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundInvesting")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorRelationsLead")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deal");
                });
#pragma warning restore 612, 618
        }
    }
}
